spring:
  profiles:
    default: hao
  data:
    mongodb:
      uri: mongodb+srv://user:user@cluster0.gw7id.mongodb.net/qrnotify?retryWrites=true&w=majority
server:
  port: 8081
chen:
  base_path: /nebrija/qrnotify-admin
twilio:
  account_sid: AC3325644bb87591e9461f745ff1810711
  auth_token: f476a993f413377b080a47152ea0f248
  phone_number: +15075194910
okta:
  oauth2:
    issuer: https://dev-86838266.okta.com/oauth2/default
    client-id: 0oa9aooq57mOsWVPZ5d7
    client-secret: WLZOlqHkVaGfcqr8exLBGuydvrskAQcrH2az9R6s
    scope: hao
  client:
    token: 008vnWH92ZUN3tJp4NRGWQpdL97XExiqjq6mvRAncJ
    orgUrl: https://dev-86838266.okta.com
qrnotify:
  feign:
    topic: http://localhost:8080/nebrija/qrnotify-topic/
