spring:
  data:
    mongodb:
      uri: ${MONGODB_URL}
server:
  port: 8080
chen:
  base_path: /nebrija/qrnotify-admin
twilio:
  account_sid: ${TWILIO_SID}
  auth_token: ${TWILIO_TOKEN}
  phone_number: ${TWILIO_NUMBER}
okta:
  oauth2:
    issuer: ${OKTA_DOMAIN}
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
    scope: hao
qrnotify:
  feign:
    topic: https://qrnotify-topic.herokuapp.com/nebrija/qrnotify-admin